name: lvlmindbeta
description: A e-learning app project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/Josoa886/lvlmindapp/
homepage: https://github.com/Josoa886/lvlmindapp
maintainer: Josoa (@Josoa886) & Fiatoa (foulburst)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  simple_gradient_text: ^1.3.0
  flutter_svg: ^0.21.0
  url_launcher: ^6.0.6


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_launcher_icons: ^0.11.0
  video_player: ^2.8.1
  chewie: ^1.5.0
  image_picker: ^1.0.4
  popover: ^0.2.8+2
  iconsax_flutter: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0
  
flutter_launcher_icons:
    android: true
    ios: true
    image_path: "images/lvlmindico.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - images/ispm.jpg
    - images/lvlmind.jpg
    - images/logomin.jpg
    - images/lvlind10.jpg
    - images/fond1 1.jpg
    - images/fond3 1.jpg
    - images/Ellipse 2.svg
    - images/Vector.svg
    - images/Vector (1).svg
    - images/Vector (2).svg
    - images/LevelMind.svg
    - images/lvlmindico.png
    - fonts/
    - videos/
    - json/matiere.json
  
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  fonts:
    - family: PatrickHand 
      fonts:
      - asset: fonts/PatrickHandSC-Regular.ttf

    - family: Josefin
      fonts:
      - asset: fonts/JosefinSans-SemiBold.ttf
    
    - family: TiltNeon 
      fonts:
      - asset: fonts/TiltNeon-Regular-VariableFont_XROT,YROT.ttf

    - family: Adlam 
      fonts:
      - asset: fonts/ADLaMDisplay-Regular.ttf
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
